title: Site
preset: page
sections:

  list: 
    type: pages
    headline: Pages
    status: published
    templates: 
      - channels
      - videos

  # homeHighlight:
  #   type: fields
  #   fields: 

  #     mode:
  #       type: radio
  #       options: 
  #         live: Live stream
  #         random: Random videos